server:
  port: ${SERVER_PORT:8084}
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5436/notification_db}
    username: ${DB_USER:notification}
    password: ${DB_PASSWORD:notification}
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
