apiVersion: v1
kind: Namespace
metadata:
  name: banking
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
  namespace: banking
data:
  RABBITMQ_HOST: rabbitmq
  ACCOUNT_SERVICE_BASE_URL: http://account-service:8082
  CUSTOMER_SERVICE_BASE_URL: http://customer-service:8081
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: banking
type: Opaque
stringData:
  customer-db-password: customer
  account-db-password: account
  transaction-db-password: transaction
  notification-db-password: notification
