server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://account-db:5432/account_db
    username: account
    password: account

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
